[package]
name = "mercury"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.42", features = ["serde"] }
rocket = "0.5.1"
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread"] }
tokio-postgres = "0.7.15"
uuid = { version = "1.18.1", features = ["v4"] }
